In [1]:
import pandas as pd

In [2]:
model_columns=['Sequence', 'ModelDomain', 'Model', 'ModelType', 'Class',
       'ClassDescription', 'Attribute', 'AttributeDescription', 'DataType',
       'Context', 'SubContext', 'Nulls', 'Is PK']

In [3]:
md_name = "Inventory"
m_name = "Simple ERD Model - Inventory"
m_type = "Physical"
rows = [
    [1, md_name, m_name, m_type, "Product", "Individual products and their descriptions", 
    "p_id", "Id field of the product by which it is coded", 
    "integer", None, None, "No", "Yes"],
    [2, md_name, m_name, m_type, "Product", "Individual products and their descriptions", 
    "p_name", "Name of the product.", 
    "string", None, None, "No", "No"],
    [3, md_name, m_name, m_type, "Location", "Facility/Building operated by the organisation", 
    "loc_id", "Id field of the location.", 
    "integer", None, None, "No", "Yes"],
    [4, md_name, m_name, m_type, "Location", "Facility/Building operated by the organisation", 
    "loc_name", "Name by which the location is known.", 
    "string", None, None, "No", "No"],
    [5, md_name, m_name, m_type, "Inventory", "Inventory of products located at a location", 
    "loc_id", "Identity of the location.", 
    "integer", None, None, "No", "Yes"],
    [6, md_name, m_name, m_type, "Inventory", "Inventory of products located at a location", 
    "p_id", "Identity of the product.", 
    "integer", None, None, "No", "Yes"],
    [7, md_name, m_name, m_type, "Inventory", "Inventory of products located at a location", 
    "p_loc_count", "Count of the product at this location.", 
    "integer", None, None, "No", "No"]    
]

In [4]:
relation_columns = [
               'Sequence',
               'ModelDomain', 
               'Model', 
               "Relationship", 
               "FromClass",
               "FromAttribute", 
               "FromCardinality",
               "ToClass",
               "ToAttribute",
               "ToCardinality" ]

relationship_rows = [[8,md_name, m_name, "Inventory --> Product", "Inventory", "p_id", "Many", "Product", "p_id", "Many"], 
                     [9,md_name, m_name, "Inventory --> Location", "Inventory", "loc_id", "Many", "Location", "loc_id", "Many"]
                    ]

In [5]:
df = pd.DataFrame(rows, columns=model_columns)
rel_df = pd.DataFrame(relationship_rows, columns=relation_columns)

model_df = pd.concat([df, rel_df])

model_df.set_index("Sequence", inplace=True)

In [6]:
model_df.to_csv("sample/inventory_v1.csv")

In [7]:
# Version 2
# Add product description and category fields
# Add staff table
# Add roles table
new_rows = [
    [10, md_name, m_name, m_type, "Product", "Individual products and their descriptions", 
    "description", "Description of the product.", 
    "string", None, None, "No", "No"],
    [11, md_name, m_name, m_type, "Staff", "Members of staff", 
    "staff_id", "Id number of the staff member.", 
    "integer", None, None, "No", "Yes"],
    [12, md_name, m_name, m_type, "Staff", "Members of staff", 
    "staff_name", "Name of the staff member.", 
    "string", None, None, "No", "No"],
    [13, md_name, m_name, m_type, "Staff", "Members of staff", 
    "loc_id", "Location base of this member of staff.", 
    "integer", None, None, "No", "No"],
    [14, md_name, m_name, m_type, "Staff", "Members of staff", 
    "role_id", "Assigned role to this member of staff", 
    "integer", None, None, "No", "No"],
    [15, md_name, m_name, m_type, "Roles", "Working Roles", 
    "role_id", "Role Identifier.", 
    "integer", None, None, "No", "Yes"],
    [16, md_name, m_name, m_type, "Roles", "Working Roles", 
    "role_name", "Role Name."]
]
    
new_rels = [
    [17,md_name, m_name, "Staff --> Location", "Staff", "loc_id", "Many", "Location", "loc_id", "One"], 
    [18,md_name, m_name, "Staff --> Role", "Staff", "role_id", "Many", "Role", "role_id", "One"]
    ]

    
df = pd.DataFrame(new_rows, columns=model_columns)
rel_df = pd.DataFrame(new_rels, columns=relation_columns)
new_model_df = pd.concat([df, rel_df])
new_model_df.set_index("Sequence", inplace=True)

In [8]:
model_df = pd.concat([model_df,new_model_df])
model_df.to_csv("sample/inventory_v2.csv")

In [10]:
new_rows = [
    [19, md_name, m_name, m_type, "PriceHistory", "Prices for each product over time.", 
    "p_id", "Product Id.", 
    "integer", None, None, "No", "Yes"],
    [20, md_name, m_name, m_type, "PriceHistory", "Prices for each product over time.", 
    "start_date", "Date the price came into effect.", 
    "datetime", None, None, "No", "Yes"],
    [21, md_name, m_name, m_type, "PriceHistory", "Prices for each product over time.", 
    "price", "Cash value associated with the product.", 
    "float", None, None, "No", "No"],
    [22, md_name, m_name, m_type, "PriceHistory", "Prices for each product over time.", 
    "price_currency", "Currency code of the price.", 
    "string", None, None, "No", "No"],
    [23, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "orderitem_id", "Unique Id for this order item", 
    "integer", None, None, "No", "Yes"],
    [24, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "qorder_id", "Identifier for the parent quote/order.", 
    "integer", None, None, "No", "Yes"],
    [25, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "p_id", "Product Identifier.", 
    "integer", None, None, "No", "No"],
    [26, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "price_per_unit", "Base price per unit.", 
    "float", None, None, "No", "No"],
    [27, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "units", "Count of product units quoted/ordered.", 
    "integer", None, None, "No", "No"],
    [28, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "discount", "Proportion of discount to be applied to base price", 
    "float", None, None, "No", "No"],
    [29, md_name, m_name, m_type, "OrderItem", "A line item that exists on a quote or order", 
    "total_price", "Final total price for this line item after discounting", 
    "float", None, None, "No", "No"],
    [30, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "quorder_id", "Unique Identifier for this qoute/order.", 
    "integer", None, None, "No", "Yes"],
    [31, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "sales_staff_id", "Staff id of salesperson responsible for sale or quote.", 
    "integer", None, None, "No", "No"],
    [32, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "quote_date", "Date used for calculating base prices.", 
    "datetime", None, None, "No", "No"],
    [33, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_name", "Name of customer.", 
    "string", None, None, "No", "No"],
    [34, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_address_line_1", "First line of customer address.", 
    "string", None, None, "No", "No"],
    [35, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_address_line_2", "Second line of customer address.", 
    "string", None, None, "No", "No"],
    [36, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_address_line_3", "Third line of customer address.", 
    "string", None, None, "No", "No"],
    [37, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_postal_town", "Customer address town.", 
    "string", None, None, "No", "No"],
    [38, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_postal_code", "Customer address post-code.", 
    "string", None, None, "No", "No"],
    [39, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "customer_phone_number", "Customer Phone Number.", 
    "string", None, None, "No", "No"],
    [40, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "quote_order_status", "Indicator showing if this record is an order or a quote.", 
    "string", None, None, "No", "No"],
    [41, md_name, m_name, m_type, "QOrder", "A quote or order.", 
    "payment_status", "Indicator showing if the order has been paid.", 
    "boolean", None, None, "No", "No"]    
]

new_rels = [
    [42,md_name, m_name, "OrderItem --> Product", "OrderItem", "order_item_id", "One", "Product", "p_id", "One"], 
    [43,md_name, m_name, "QOrder --> OrderItem", "QOrder", "qorder_id", "One", "OrderItem", "qorder_id", "Many"],
    [44,md_name, m_name, "QOrder --> Staff", "QOrder", "staff_id", "One", "Staff", "staff_id", "Many"]
    ]

df = pd.DataFrame(new_rows, columns=model_columns)
rel_df = pd.DataFrame(new_rels, columns=relation_columns)
new_model_df = pd.concat([df, rel_df])
new_model_df.set_index("Sequence", inplace=True)

In [11]:
model_df = pd.concat([model_df,new_model_df])

In [12]:
model_df

,ModelDomain,Model,ModelType,Class,ClassDescription,Attribute,AttributeDescription,DataType,Context,SubContext,Nulls,Is PK,Relationship,FromClass,FromAttribute,FromCardinality,ToClass,ToAttribute,ToCardinality
Sequence,,,,,,,,,,,,,,,,,,,
1,Inventory,Simple ERD Model - Inventory,Physical,Product,Individual products and their descriptions,p_id,Id field of the product by which it is coded,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Inventory,Simple ERD Model - Inventory,Physical,Product,Individual products and their descriptions,p_name,Name of the product.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Inventory,Simple ERD Model - Inventory,Physical,Location,Facility/Building operated by the organisation,loc_id,Id field of the location.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Inventory,Simple ERD Model - Inventory,Physical,Location,Facility/Building operated by the organisation,loc_name,Name by which the location is known.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Inventory,Simple ERD Model - Inventory,Physical,Inventory,Inventory of products located at a location,loc_id,Identity of the location.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Inventory,Simple ERD Model - Inventory,Physical,Inventory,Inventory of products located at a location,p_id,Identity of the product.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Inventory,Simple ERD Model - Inventory,Physical,Inventory,Inventory of products located at a location,p_loc_count,Count of the product at this location.,integer,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Inventory --> Product,Inventory,p_id,Many,Product,p_id,Many
9,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Inventory --> Location,Inventory,loc_id,Many,Location,loc_id,Many
10,Inventory,Simple ERD Model - Inventory,Physical,Product,Individual products and their descriptions,description,Description of the product.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Inventory,Simple ERD Model - Inventory,Physical,Staff,Members of staff,staff_id,Id number of the staff member.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Inventory,Simple ERD Model - Inventory,Physical,Staff,Members of staff,staff_name,Name of the staff member.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Inventory,Simple ERD Model - Inventory,Physical,Staff,Members of staff,loc_id,Location base of this member of staff.,integer,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Inventory,Simple ERD Model - Inventory,Physical,Staff,Members of staff,role_id,Assigned role to this member of staff,integer,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Inventory,Simple ERD Model - Inventory,Physical,Roles,Working Roles,role_id,Role Identifier.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Inventory,Simple ERD Model - Inventory,Physical,Roles,Working Roles,role_name,Role Name.,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staff --> Location,Staff,loc_id,Many,Location,loc_id,One
18,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Staff --> Role,Staff,role_id,Many,Role,role_id,One
19,Inventory,Simple ERD Model - Inventory,Physical,PriceHistory,Prices for each product over time.,p_id,Product Id.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Inventory,Simple ERD Model - Inventory,Physical,PriceHistory,Prices for each product over time.,start_date,Date the price came into effect.,datetime,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Inventory,Simple ERD Model - Inventory,Physical,PriceHistory,Prices for each product over time.,price,Cash value associated with the product.,float,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Inventory,Simple ERD Model - Inventory,Physical,PriceHistory,Prices for each product over time.,price_currency,Currency code of the price.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,orderitem_id,Unique Id for this order item,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,qorder_id,Identifier for the parent quote/order.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,p_id,Product Identifier.,integer,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,price_per_unit,Base price per unit.,float,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,units,Count of product units quoted/ordered.,integer,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,discount,Proportion of discount to be applied to base p...,float,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Inventory,Simple ERD Model - Inventory,Physical,OrderItem,A line item that exists on a quote or order,total_price,Final total price for this line item after dis...,float,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,quorder_id,Unique Identifier for this qoute/order.,integer,None,None,No,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,sales_staff_id,Staff id of salesperson responsible for sale o...,integer,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,quote_date,Date used for calculating base prices.,datetime,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_name,Name of customer.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_address_line_1,First line of customer address.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_address_line_2,Second line of customer address.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_address_line_3,Third line of customer address.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_postal_town,Customer address town.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_postal_code,Customer address post-code.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,customer_phone_number,Customer Phone Number.,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,quote_order_status,Indicator showing if this record is an order o...,string,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Inventory,Simple ERD Model - Inventory,Physical,QOrder,A quote or order.,payment_status,Indicator showing if the order has been paid.,boolean,None,None,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,OrderItem --> Product,OrderItem,order_item_id,One,Product,p_id,One
43,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QOrder --> OrderItem,QOrder,qorder_id,One,OrderItem,qorder_id,Many
44,Inventory,Simple ERD Model - Inventory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QOrder --> Staff,QOrder,staff_id,One,Staff,staff_id,Many

In [13]:
model_df.to_csv("sample/inventory_v3.csv")