In [1]:
from IPython.display import display, Image, HTML

In [2]:
import sys, os
module_path = os.path.abspath(os.path.join('../src/'))
if module_path not in sys.path:
    sys.path.append(module_path)

print(sys.path)
import repository

['/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/tomk/environment/devpy/lib/python3.10/site-packages', '/home/tomk/Documents/Coding/gitHub/daglit/src', '/home/tomk/Documents/Coding/gitHub/datamodels/src']
Serialization.Meta [Serialization.SerializationMetaData]
Serialization.Serialization [Serialization.SerializationSpecs]
Serialization.Mapping [Serialization.SerializationSpecs]
Serialization.TranslationMapping [Serialization.SerializationSpecs]
Serialization.MappingKVPair [Serialization.SerializationSpecs]
Serialization.MetaClass [Serialization.Meta]
Serialization.MetaDataProperty [Serialization.Meta]
Serialization.MetaProperty [Serialization.Meta]
Serialization.MetaStaticProperty [Serialization.Meta]
Serialization.BatchDefinition [Serialization.SerializationSpecs]
Serialization.SerializationSpecs [Serialization.SerializationMetaData]

* Owlready2 * WARNING: ObjectProperty http://www.tkltd.org/ontologies/serialization#MappingMetaTarget belongs to more than one entity types: [owl.AnnotationProperty, owl.ObjectProperty, owl.topObjectProperty]; I'm trying to fix it...
* Owlready2 * Running HermiT...
    java -Xmx2000M -cp /home/tomk/environment/devpy/lib/python3.10/site-packages/owlready2/hermit:/home/tomk/environment/devpy/lib/python3.10/site-packages/owlready2/hermit/HermiT.jar org.semanticweb.HermiT.cli.CommandLine -c -O -D -I file:////tmp/tmp7jl0jm68

Serialization.BatchNode [Serialization.DataLoad]
Serialization.DataLoad [Serialization.SerializationMetaData]
Serialization.SerializationMetaData [owl.Thing]
Serialization.DataPropertyMapping [Serialization.Mapping]
Serialization.EntityMapping [Serialization.Mapping]
Serialization.JobNode [Serialization.DataLoad]
Serialization.PropertyMapping [Serialization.Mapping]
Serialization.RowNode [Serialization.DataLoad]

* Owlready2 * HermiT took 0.696845531463623 seconds
* Owlready * (NB: only changes on entities loaded in Python are shown, other changes are done but not listed)

In [3]:
import os

In [4]:
from rdflib import URIRef, Graph, Namespace, Literal
import pandas as pd
import re

In [5]:
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
#chrome_options.add_argument("--headless")
driver = webdriver.Chrome(options=chrome_options)
#driver.get('http://selenium.dev')
html_content="""
<html>
	<head>
        <link rel="stylesheet" type="text/css" href="../flask-app/static/reset.css">
        <link rel="stylesheet" type="text/css" href="../flask-app/static/tkl_style.css">
    </head>
	<body> 
		<div>
			<p>Test Page</>
            <table id="test1">
                <tbody>
                <tr><th>Oh</th><th>One</th><th>Two</th><th>Three</th><th>Four</th></tr>
                <tr><td>Oh</td><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                </tbody>
            </table>

            <table id="test2">
                <tbody>
                <tr><th>Oh</th><th>One</th><th>Two</th><th>Three</th><th>Four</th></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Mary had a little lamb.<br>Its fleece as white as snow.<br>And everywhere that Mary went<br>The lamb was sure to go.</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                </tbody>
            </table>
		</div>
	</body>
</html>
"""

with open("html_test_page.html", "w") as save:
    save.write(html_content)

fullpath = os.path.abspath("html_test_page.html")
print(fullpath)
#driver.get("data:text/html;charset=utf-8,"+html_content)
driver.get(f"file://{fullpath}")
th = driver.execute_script("return document.table_height;")
th = driver.execute_script("""
var dict = new Object();
var a ;
var b ;
for (let i = 1; i < 3; i++) {
    let a=document.getElementById("test"+i).clientWidth;
    let b=document.getElementById("test"+i).clientHeight;
    dict["test"+i] = [a,b];
}
return dict
    
    """)
#driver.quit()
th

/home/tomk/Documents/Coding/gitHub/datamodels/IDE/html_test_page.html

{'test1': [193, 76], 'test2': [367, 570]}

In [6]:
HTML("""<html>
	<head>
        <link rel="stylesheet" href="../flask-app/static/reset.css">
        <link rel="stylesheet" href="../flask-app/static/tkl_style.css">
    </head>
	<body> 
		<div>
			<p>Test Page</>
            <table id="test1">
                <tbody>
                <tr><th>Oh</th><th>One</th><th>Two</th><th>Three</th><th>Four</th></tr>
                <tr><td>Oh</td><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                </tbody>
            </table>

            <table id="test2">
                <tbody>
                <tr><th>Oh</th><th>One</th><th>Two</th><th>Three</th><th>Four</th></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                <tr><th>Oh</th><td>One</td><td>Two</td><td>Three</td><td>Four</td></tr>
                </tbody>
            </table>
		</div>
	</body>
</html>""")

In [7]:
q_template={ "self" : "PARAMETER(@selfuri)",
    "contents" : {  "label" : "SPARQL(SELECT ?label WHERE {@selfuri <http://www.w3.org/2000/01/rdf-schema#label> ?label})", 
                    "type" : "SPARQL(SELECT ?type WHERE {@selfuri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?type})",
                    "description" : "SPARQL(SELECT ?description WHERE {@selfuri <http://www.tkltd.org/ontologies/datamodel#Description> ?description})",
                    "identifier" : "SPARQL(SELECT ?identifier WHERE {@selfuri <http://www.tkltd.org/ontologies/serialization#UniqueIdentifier> ?identifier})",
                    "@attributeuri" : "SPARQL(SELECT ?attributeuri WHERE {@selfuri <http://www.tkltd.org/ontologies/datamodel#ClassContainsAttribute> ?attributeuri})",
                    "attributes" : { 
                        "self" : "PARAMETER(@attributeuri)",
                        "contents" : {
                            "label" : "SPARQL(SELECT ?label WHERE {@attributeuri <http://www.w3.org/2000/01/rdf-schema#label> ?label})", 
                            "datatype" : "SPARQL(SELECT ?datatype WHERE {@attributeuri <http://www.tkltd.org/ontologies/datamodel#DataType> ?datatype})",
                            "nulls" : "SPARQL(SELECT ?nulls WHERE {@attributeuri <http://www.tkltd.org/ontologies/datamodel#NullsOptional> ?nulls})",
                            "optionality" : "SPARQL(SELECT ?optionality WHERE {@attributeuri <http://www.tkltd.org/ontologies/datamodel#Optionality> ?optionality})",
                            "pk" : "SPARQL(SELECT ?pk WHERE {@attributeuri <http://www.tkltd.org/ontologies/datamodel#isIdentifierForClass> ?pk})",
                            "identifier" : "SPARQL(SELECT ?identifier WHERE {@attributeuri <http://www.tkltd.org/ontologies/serialization#UniqueIdentifier> ?identifier})",
                            "description" : "SPARQL(SELECT ?description WHERE {@attributeuri <http://www.tkltd.org/ontologies/datamodel#Description> ?description})",



                        }
                    }

}
    

}

In [8]:
def to_text(something, context=None):
    if context is None:
        if isinstance(something, (URIRef, Literal)):
            return something.toPython()
        elif isinstance(something, str):
            return something
        else:
            return str(something)
    elif context=="sparql":
        if isinstance(something, (URIRef, Literal)):
            return something.n3()
        elif isinstance(something, str):
            return something
        else:
            return str(something)

def multi_replace(text, replace_parms, parameters):
    for p in replace_parms:
        text=text.replace(p, to_text(parameters.get(p, None), context="sparql"))
    return text

def resolve_content(graph, content, parameters, scope):
    # Given a string, unpack and resolve to some list of results
    # parameters hosts global list of parameter options, while
    # scope contains the current working values being processed
    value_type_rx=re.compile("(SPARQL|PARAMETER)\((.*)\)")
    match_groups=value_type_rx.findall(content)
    if match_groups is not None and len(match_groups)>0:
        m_type, m_value = match_groups[0]
    if m_type.lower()=="parameter":
        r_val = [m_value,parameters.get(m_value, None)]
        return r_val
    elif m_type.lower()=="sparql":
        get_parms_rx=re.compile("\@[\w]*")
        replace_parms = get_parms_rx.findall(m_value)
        query = multi_replace(m_value, replace_parms, scope)
        rs =  g.query(query)
        return [v[0] for v in list(rs)]
    

def qt_dict(graph, template, parameters, scope=None):
    """Run through a node_properties extract template, each section containing a
    self and contents section. 
    The self section defines a key value which is drawn from parameters and assigned to
    the scope. """
    return_d = dict()
    if scope is None:
        scope=dict()
    self_key_content = template.get('self', None)
    
    self_key_name, self_key_list=resolve_content(graph, self_key_content, parameters, scope)
    for key in self_key_list:
        return_d[key]=dict()
        scope[self_key_name]=key
        for header, specification in template.get('contents', {}).items():
            if not isinstance(specification, dict):
                resolved_content=resolve_content(graph, specification, parameters, scope)
                return_d[key][header]=resolved_content
                if header[0]=="@":
                    parameters={**parameters, **{header:resolved_content}}
            else:
                return_d[key][header]=qt_dict(graph, template.get('contents').get(header), parameters, scope)
    return return_d

In [9]:
store_type="jena"
#store_type="memory"
repo = repository.Repository(store_type=store_type)

In [10]:
q="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

select ?s ?p ?o
    WHERE
    {GRAPH ?g { ?s ?p ?o. }
FILTER (?g=<http://discourse>)
}
"""
q="""
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

select ?s ?p ?o
    WHERE
    {GRAPH ?g { ?s ?p ?o. }
FILTER (?g=<http://discourse>)
FILTER (?p=<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
FILTER (?o=<http://www.tkltd.org/ontologies/discourse#Discourse>)
}
"""

rs=repo.ds.query(q)
pd.DataFrame([r[0] for r in rs]).values

array([[rdflib.term.URIRef('http://www.tkltd.org/ontologies/21339b0a757045dd9ad49d3511edaaff')],
       [rdflib.term.URIRef('http://www.tkltd.org/ontologies/b44fb8862f184e5caec0e920431e7ae3')],
       [rdflib.term.URIRef('http://www.tkltd.org/ontologies/92fb95a62182485aa517e6de04add5e6')],
       [rdflib.term.URIRef('http://www.tkltd.org/ontologies/5384647aafb44a2699b027da7838341a')],
       [rdflib.term.URIRef('http://www.tkltd.org/ontologies/7deb9411c2764d5996469b4b95cd9436')],
       [rdflib.term.URIRef('http://www.tkltd.org/ontologies/db9a929289404cb2840151ed991e3725')]],
      dtype=object)

In [11]:
discourse_e=URIRef('http://www.tkltd.org/ontologies/92fb95a62182485aa517e6de04add5e6')
qr = repo.run_cached_query("get_discourse_posits_parms_discourse_iris.sparql", parameters=[discourse_e.n3()], native_rdflib=True)
model = URIRef('http://www.tkltd.org/ontologies/214bc10fb39f4a418e44ba9f3ad78803')
pd.DataFrame(qr)
g=Graph()
for row in qr:
        g.add((row['s'], row['p'], row['o']))

print(len(g))

('%%p0%%', '<http://www.tkltd.org/ontologies/92fb95a62182485aa517e6de04add5e6>')
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX disco: <http://www.tkltd.org/ontologies/discourse#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?discourse ?assertion ?refutation ?posit ?s ?p ?o
FROM <http://discourse>
WHERE {

  {
      ?discourse a disco:Discourse.
      ?discourse disco:DiscourseContains+ ?declaration .
      ?declaration a disco:Declaration .
        OPTIONAL { ?declaration disco:Asserts ?assertion.
                   ?assertion disco:Subject ?s.
                   ?assertion disco:Predicate ?p.
                   ?assertion disco:Object ?o.
                   }
        OPTIONAL { ?declaration disco:Refutes ?refutation.
                   ?refutation disco:Subject ?s.
                   ?refutation disco:Predicate ?p.
                   ?refutation disco:Object ?o.
                   }
        OPTIONAL { ?declaration disco:Posits ?posit.
                   ?posit disco:Subject ?s.
                   ?posit disco:Predicate ?p.
                   ?posit disco:Object ?o.
        }
      FILTER (?discourse IN ( <http://www.tkltd.org/ontologies/92fb95a62182485aa517e6de04add5e6> )) .

  }
}
494

In [12]:
entity_query="""
SELECT ?s 
WHERE {
 ?s a <http://www.tkltd.org/ontologies/datamodel#Class>.
}
"""
entity_list = [v[0] for v in list(g.query(entity_query))]
entity_list

[rdflib.term.URIRef('http://www.tkltd.org/ontologies/f99a8e3897434f4eb9ba375b05ad182b'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/37bf07d15e264bdc8c3fb17369bef0c6'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/27f7c559482b45afa110eeba5518ff45'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/0ca5aa25011b4d209bce931b35a9fe33'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/8cec6c4c8ebf4b6da9bd2557d44aeaea'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/e8ec4d3d6c2f42ea9efea0509d98abc4'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/25ac78e9ccdf4bbdbd0a144a31e0a79e'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/e82395098d9b40f3b5c7c0d3458e887e'),
 rdflib.term.URIRef('http://www.tkltd.org/ontologies/d35da2fdc8474d2eb99f73eb9f02f0f5')]

In [13]:
e1=URIRef('http://www.tkltd.org/ontologies/f333cfb4946a4ce08a30ccb227e6ed76')
e2=URIRef('http://www.tkltd.org/ontologies/8c8a40c3031549d6b56233892cac65bc')

#rs = resolve_content(g, "SPARQL(SELECT ?attributeuri WHERE {@selfuri <http://www.tkltd.org/ontologies/datamodel#ClassContainsAttribute> ?attributeuri})", {"@selfuri" : [e1, e2]}, {"@selfuri" : e1})

qt_d = qt_dict(g, q_template, {"@selfuri" : entity_list}, scope=None)

In [14]:
for i,d in qt_d.items():
    print(i)
    for k,v in qt_d[i].items():
        if isinstance(v, list) and k[0]!="@":
            print ("\t", k, ":", ",".join([l for l in v]))
        if isinstance(v, dict):
            print ("\t", k )
            for kk,vv in v.items():
                for kkk,vvv in vv.items():
                    print ("\t\t", kkk, ":", ". ".join([l for l in vvv]))
                print()
    print()

http://www.tkltd.org/ontologies/f99a8e3897434f4eb9ba375b05ad182b
	 label : Location
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : Facility/Building operated by the organisation
	 identifier : Inventory.Inventory.Location
	 attributes
		 label : loc_name
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Location.loc_name
		 description : Name by which the location is known.

		 label : loc_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Location.loc_id
		 description : Id field of the location.


http://www.tkltd.org/ontologies/37bf07d15e264bdc8c3fb17369bef0c6
	 label : Inventory
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : Inventory of products located at a location
	 identifier : Inventory.Inventory.Inventory
	 attributes
		 label : p_loc_count
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Inventory.p_loc_count
		 description : Count of the product at this location.

		 label : p_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Inventory.p_id
		 description : Identity of the product.

		 label : loc_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Inventory.loc_id
		 description : Identity of the location.


http://www.tkltd.org/ontologies/27f7c559482b45afa110eeba5518ff45
	 label : Product
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : Individual products and their descriptions
	 identifier : Inventory.Inventory.Product
	 attributes
		 label : description
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Product.description
		 description : Description of the product.

		 label : p_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Product.p_id
		 description : Id field of the product by which it is coded

		 label : p_name
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Product.p_name
		 description : Unique name of the product.


http://www.tkltd.org/ontologies/0ca5aa25011b4d209bce931b35a9fe33
	 label : OrderItem
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : A line item that exists on a quote or order
	 identifier : Inventory.Inventory.OrderItem
	 attributes
		 label : discount
		 datatype : float
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.OrderItem.discount
		 description : Proportion of discount to be applied to base price

		 label : units
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.OrderItem.units
		 description : Count of product units quoted/ordered.

		 label : total_price
		 datatype : float
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.OrderItem.total_price
		 description : Final total price for this line item after discounting

		 label : order_item_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.OrderItem.order_item_id
		 description : Unique Id for this order item

		 label : p_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.OrderItem.p_id
		 description : Product Identifier.

		 label : qorder_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.OrderItem.qorder_id
		 description : Identifier for the parent quote/order.

		 label : price_per_unit
		 datatype : float
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.OrderItem.price_per_unit
		 description : Base price per unit.


http://www.tkltd.org/ontologies/8cec6c4c8ebf4b6da9bd2557d44aeaea
	 label : PriceHistory
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : Prices for each product over time.
	 identifier : Inventory.Inventory.PriceHistory
	 attributes
		 label : start_date
		 datatype : datetime
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.PriceHistory.start_date
		 description : Date the price came into effect.

		 label : price_currency
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.PriceHistory.price_currency
		 description : Currency code of the price.

		 label : p_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.PriceHistory.p_id
		 description : Product Id.

		 label : price
		 datatype : float
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.PriceHistory.price
		 description : Cash value associated with the product.


http://www.tkltd.org/ontologies/e8ec4d3d6c2f42ea9efea0509d98abc4
	 label : Customer
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : An individual who is involved in a quote or order. Subject to GDPR regulations.
	 identifier : Inventory.Inventory.Customer
	 attributes
		 label : address_line_3
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.address_line_3
		 description : Third line of customer address.

		 label : customer_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Customer.customer_id
		 description : Individual customer identifier

		 label : address_line_1
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.address_line_1
		 description : First line of customer address.

		 label : surname
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.surname
		 description : Surname of customer.

		 label : postal_town
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.postal_town
		 description : Customer address town.

		 label : forename
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.forename
		 description : Forename of customer.

		 label : postal_code
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.postal_code
		 description : Customer address post-code.

		 label : phone_number
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.phone_number
		 description : Customer Phone Number.

		 label : address_line_2
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Customer.address_line_2
		 description : Second line of customer address.


http://www.tkltd.org/ontologies/25ac78e9ccdf4bbdbd0a144a31e0a79e
	 label : Roles
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : Working Roles
	 identifier : Inventory.Inventory.Roles
	 attributes
		 label : role_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Roles.role_id
		 description : Role Identifier.

		 label : role_name
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Roles.role_name
		 description : Role Name.


http://www.tkltd.org/ontologies/e82395098d9b40f3b5c7c0d3458e887e
	 label : Staff
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : Members of staff
	 identifier : Inventory.Inventory.Staff
	 attributes
		 label : role_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Staff.role_id
		 description : Assigned role to this member of staff

		 label : staff_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.Staff.staff_id
		 description : Id number of the staff member.

		 label : loc_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Staff.loc_id
		 description : Location base of this member of staff.

		 label : surname
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Staff.surname
		 description : Surname of the staff member.

		 label : forename
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.Staff.forename
		 description : Forename of the staff member.


http://www.tkltd.org/ontologies/d35da2fdc8474d2eb99f73eb9f02f0f5
	 label : QOrder
	 type : http://www.tkltd.org/ontologies/datamodel#Class
	 description : A normalised quote or order. FK link to Customer.
	 identifier : Inventory.Inventory.QOrder
	 attributes
		 label : sales_staff_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.QOrder.sales_staff_id
		 description : Who made the quote or order?

		 label : payment_status
		 datatype : boolean
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.QOrder.payment_status
		 description : Indicator showing if the order has been paid.

		 label : quote_date
		 datatype : datetime
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.QOrder.quote_date
		 description : Date used for calculating base prices.

		 label : customer_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.QOrder.customer_id
		 description : Individual customer identifier.

		 label : qorder_id
		 datatype : integer
		 nulls :
		 optionality : No
		 pk : Yes
		 identifier : Inventory.Inventory.QOrder.qorder_id
		 description : Unique Identifier for this qoute/order. Previously, customer was denormalised(?)

		 label : quote_order_status
		 datatype : string
		 nulls :
		 optionality : No
		 pk : No
		 identifier : Inventory.Inventory.QOrder.quote_order_status
		 description : Indicator showing if this record is an order or a quote.

In [15]:
qt_d.keys()

dict_keys([rdflib.term.URIRef('http://www.tkltd.org/ontologies/f99a8e3897434f4eb9ba375b05ad182b'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/37bf07d15e264bdc8c3fb17369bef0c6'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/27f7c559482b45afa110eeba5518ff45'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/0ca5aa25011b4d209bce931b35a9fe33'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/8cec6c4c8ebf4b6da9bd2557d44aeaea'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/e8ec4d3d6c2f42ea9efea0509d98abc4'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/25ac78e9ccdf4bbdbd0a144a31e0a79e'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/e82395098d9b40f3b5c7c0d3458e887e'), rdflib.term.URIRef('http://www.tkltd.org/ontologies/d35da2fdc8474d2eb99f73eb9f02f0f5')])

In [16]:
customer = URIRef('http://www.tkltd.org/ontologies/e8ec4d3d6c2f42ea9efea0509d98abc4')
product = URIRef('http://www.tkltd.org/ontologies/27f7c559482b45afa110eeba5518ff45')
location = URIRef('http://www.tkltd.org/ontologies/f99a8e3897434f4eb9ba375b05ad182b')
inventory = URIRef('http://www.tkltd.org/ontologies/37bf07d15e264bdc8c3fb17369bef0c6')
orderitem = URIRef('http://www.tkltd.org/ontologies/0ca5aa25011b4d209bce931b35a9fe33')
price_history = URIRef('http://www.tkltd.org/ontologies/8cec6c4c8ebf4b6da9bd2557d44aeaea')
customer = URIRef('http://www.tkltd.org/ontologies/e8ec4d3d6c2f42ea9efea0509d98abc4')
roles = URIRef('http://www.tkltd.org/ontologies/25ac78e9ccdf4bbdbd0a144a31e0a79e')
staff = URIRef('http://www.tkltd.org/ontologies/e82395098d9b40f3b5c7c0d3458e887e')
qorder = URIRef('http://www.tkltd.org/ontologies/d35da2fdc8474d2eb99f73eb9f02f0f5')
qt_d[customer]

{'label': [rdflib.term.Literal('Customer')],
 'type': [rdflib.term.URIRef('http://www.tkltd.org/ontologies/datamodel#Class')],
 'description': [rdflib.term.Literal('An individual who is involved in a quote or order. Subject to GDPR regulations. ')],
 'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer')],
 '@attributeuri': [rdflib.term.URIRef('http://www.tkltd.org/ontologies/6b5dff90648d413e92b9a54fdc3ae18f'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/5c1d201b0ae34695863d66f80c00ca01'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/ca3cafbc9ae5498eb104660cd1a69cae'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/c78d7221437849eda5e15d0ce7373e13'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/76a49e07ebd04f8f902c10be8c1783b0'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/058ceb8bd0ee46de80bc7cbea2570e38'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/ec0ad24135a9444dbb842f396930ba0c'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/f30d3c5ee27147a19b262260d99b6014'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/b7960b15ec6541c386cf4a2edf010db1')],
 'attributes': {rdflib.term.URIRef('http://www.tkltd.org/ontologies/6b5dff90648d413e92b9a54fdc3ae18f'): {'label': [rdflib.term.Literal('address_line_3')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.address_line_3')],
   'description': [rdflib.term.Literal('Third line of customer address.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/5c1d201b0ae34695863d66f80c00ca01'): {'label': [rdflib.term.Literal('customer_id')],
   'datatype': [rdflib.term.Literal('integer')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('Yes')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.customer_id')],
   'description': [rdflib.term.Literal('Individual customer identifier')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/ca3cafbc9ae5498eb104660cd1a69cae'): {'label': [rdflib.term.Literal('address_line_1')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.address_line_1')],
   'description': [rdflib.term.Literal('First line of customer address.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/c78d7221437849eda5e15d0ce7373e13'): {'label': [rdflib.term.Literal('surname')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.surname')],
   'description': [rdflib.term.Literal('Surname of customer.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/76a49e07ebd04f8f902c10be8c1783b0'): {'label': [rdflib.term.Literal('postal_town')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.postal_town')],
   'description': [rdflib.term.Literal('Customer address town.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/058ceb8bd0ee46de80bc7cbea2570e38'): {'label': [rdflib.term.Literal('forename')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.forename')],
   'description': [rdflib.term.Literal('Forename of customer.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/ec0ad24135a9444dbb842f396930ba0c'): {'label': [rdflib.term.Literal('postal_code')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.postal_code')],
   'description': [rdflib.term.Literal('Customer address post-code.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/f30d3c5ee27147a19b262260d99b6014'): {'label': [rdflib.term.Literal('phone_number')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.phone_number')],
   'description': [rdflib.term.Literal('Customer Phone Number.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/b7960b15ec6541c386cf4a2edf010db1'): {'label': [rdflib.term.Literal('address_line_2')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.Customer.address_line_2')],
   'description': [rdflib.term.Literal('Second line of customer address.')]}}}

In [17]:


def class_table_constructor(classdef):
    identifier = " ".join(classdef.get("identifier"))
    label = " ".join(classdef.get("label"))
    description = " ".join(classdef.get("description"))

    d_row="""        <tr>
            <td colspan="5" class="head">{description}</td>
        </tr>"""
    d_row=""

    class_d = {"identifier":identifier, 
          "label":label, 
          "description":description, 
          "d_row":d_row}

    table = """<table id="{identifier}" width="600px">
    <caption>{label}</caption>
    <thead>
    {d_row}
        <tr><th class="head" width="25%">Attribute</th><th class="head" width="40%">Description</th><th class="head" width="10%">Datatype</th><th class="head">Nulls</th><th class="head">PK</th></tr>
    </thead>
    <tbody>
    {rows}
    </tbody>
    </table>
    """
    rows = []
    rowdef = """<tr><th >{alabel}</th><td>{adescription}</td><td >{adatatype}</td><td >{anulls}</td><td >{apk}</td></tr>\n"""
    rowdef = """<tr><th >{alabel}</th><td >{adescription}</td><td>{adatatype}</td><td>{anulls}</td><td >{apk}</td></tr>\n"""
    for i,a in sorted([(i,a) for i,a in classdef.get("attributes").items() if "".join(a['pk']).lower()=="yes"],key=lambda x : "".join(x[1]['label'])):
        a_dict={"alabel":" ".join(a.get('label')),
        "adescription":" ".join(a.get('description')),
        "adatatype":" ".join(a.get('datatype')),
        "anulls":" ".join(a.get('nulls')),
        "apk":" ".join(a.get('pk'))}
        rows.append(rowdef.format(**a_dict))

    for i,a in sorted([(i,a) for i,a in classdef.get("attributes").items() if "".join(a['pk']).lower()!="yes"],key=lambda x : "".join(x[1]['label'])):
        a_dict={"alabel":" ".join(a.get('label')),
        "adescription":" ".join(a.get('description')),
        "adatatype":" ".join(a.get('datatype')),
        "anulls":" ".join(a.get('nulls')),
        "apk":" ".join(a.get('pk'))}
        rows.append(rowdef.format(**a_dict))
    rows = " ".join(rows)
    return table.format(**{**class_d, **{"rows":rows}})

In [18]:
qt_d[qorder]

{'label': [rdflib.term.Literal('QOrder')],
 'type': [rdflib.term.URIRef('http://www.tkltd.org/ontologies/datamodel#Class')],
 'description': [rdflib.term.Literal('A normalised quote or order. FK link to Customer. ')],
 'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder')],
 '@attributeuri': [rdflib.term.URIRef('http://www.tkltd.org/ontologies/6671d87d573d480f9e8b169c24435b85'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/f47c1c8293e9456f9d8d6c8914ad8dc8'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/5988fe7ed3574fc2ba7de9d74965818e'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/418f8f3c0e484891bb2a6a506432085b'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/ef8afd6df240428781355ad71c1b3728'),
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/a801f50396be453591b50e620f2dc56f')],
 'attributes': {rdflib.term.URIRef('http://www.tkltd.org/ontologies/6671d87d573d480f9e8b169c24435b85'): {'label': [rdflib.term.Literal('sales_staff_id')],
   'datatype': [rdflib.term.Literal('integer')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder.sales_staff_id')],
   'description': [rdflib.term.Literal('Who made the quote or order?')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/f47c1c8293e9456f9d8d6c8914ad8dc8'): {'label': [rdflib.term.Literal('payment_status')],
   'datatype': [rdflib.term.Literal('boolean')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder.payment_status')],
   'description': [rdflib.term.Literal('Indicator showing if the order has been paid.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/5988fe7ed3574fc2ba7de9d74965818e'): {'label': [rdflib.term.Literal('quote_date')],
   'datatype': [rdflib.term.Literal('datetime')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder.quote_date')],
   'description': [rdflib.term.Literal('Date used for calculating base prices.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/418f8f3c0e484891bb2a6a506432085b'): {'label': [rdflib.term.Literal('customer_id')],
   'datatype': [rdflib.term.Literal('integer')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder.customer_id')],
   'description': [rdflib.term.Literal('Individual customer identifier.')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/ef8afd6df240428781355ad71c1b3728'): {'label': [rdflib.term.Literal('qorder_id')],
   'datatype': [rdflib.term.Literal('integer')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('Yes')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder.qorder_id')],
   'description': [rdflib.term.Literal('Unique Identifier for this qoute/order. Previously, customer was denormalised(?)')]},
  rdflib.term.URIRef('http://www.tkltd.org/ontologies/a801f50396be453591b50e620f2dc56f'): {'label': [rdflib.term.Literal('quote_order_status')],
   'datatype': [rdflib.term.Literal('string')],
   'nulls': [],
   'optionality': [rdflib.term.Literal('No')],
   'pk': [rdflib.term.Literal('No')],
   'identifier': [rdflib.term.Literal('Inventory.Inventory.QOrder.quote_order_status')],
   'description': [rdflib.term.Literal('Indicator showing if this record is an order or a quote.')]}}}

In [19]:
print(class_table_constructor(qt_d[customer]))

<table id="Inventory.Inventory.Customer" width="600px">
    <caption>Customer</caption>
    <thead>

        <tr><th class="head" width="25%">Attribute</th><th class="head" width="40%">Description</th><th class="head" width="10%">Datatype</th><th class="head">Nulls</th><th class="head">PK</th></tr>
    </thead>
    <tbody>
    <tr><th >customer_id</th><td >Individual customer identifier</td><td>integer</td><td></td><td >Yes</td></tr>
 <tr><th >address_line_1</th><td >First line of customer address.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >address_line_2</th><td >Second line of customer address.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >address_line_3</th><td >Third line of customer address.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >forename</th><td >Forename of customer.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >phone_number</th><td >Customer Phone Number.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >postal_code</th><td >Customer address post-code.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >postal_town</th><td >Customer address town.</td><td>string</td><td></td><td >No</td></tr>
 <tr><th >surname</th><td >Surname of customer.</td><td>string</td><td></td><td >No</td></tr>

    </tbody>
    </table>

In [20]:
HTML(class_table_constructor(qt_d[customer]))

In [21]:
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

chrome_options = Options()
#chrome_options.add_argument("--headless")
driver = webdriver.Chrome(options=chrome_options)
#driver.get('http://selenium.dev')
ident_list=[]

html_content="""<html>
	<head>
        <link rel="stylesheet" href="../flask-app/static/reset.css">
        <link rel="stylesheet" href="../flask-app/static/tkl_style.css">
    </head>
    <body>
    {table_content}
    </body>
    </html>"""

html_content = html_content.format(table_content=class_table_constructor(qt_d[customer]))


ident_list.append("".join(qt_d[qorder].get("identifier")))
with open("html_test_page.html", "w") as save:
    save.write(html_content)

fullpath = os.path.abspath("html_test_page.html")
print(fullpath)
#driver.get("data:text/html;charset=utf-8,"+html_content)
driver.get(f"file://{fullpath}")
th = driver.execute_script("return document.table_height;")
th = driver.execute_script("""
var dict = new Object();
let a=document.getElementById("Inventory.Inventory.Customer").clientWidth;
let b=document.getElementById("Inventory.Inventory.Customer").clientHeight;
dict["Inventory.Inventory.Customer"] = [a,b];

return dict
    
    """)
#driver.quit()
th

/home/tomk/Documents/Coding/gitHub/datamodels/IDE/html_test_page.html

{'Inventory.Inventory.Customer': [600, 318]}

In [22]:

foreign_object_wrapper = """<foreignObject x="10" y="15" width="600" height="418">
    <body xmlns="http://www.w3.org/1999/xhtml">
        {content}
    </body>
</foreignObject>""".format(content=class_table_constructor(qt_d[customer]))

In [23]:
import panel

In [24]:
table_panel = panel.Panel(loc= (0,0), size=(620, 420), corner_radius_ratio=7, title_panel_ratio=0.25)

In [25]:
table_panel

In [26]:
def make_path(panel, title_style, panel_style):
    path1 = " ".join(panel._title_path_steps())
    path2 = " ".join(panel._panel_path_steps())
    #stroke:none; fill:url(#pink_white);
    #stroke:none; fill:url(#blue);
    svg_path1 = """<path style="{style}" d="{p}"> </path> """.format(p=path1, style=title_style)
    svg_path2 = """<path style="{style}" d="{p}"> </path> """.format(p=path2, style=panel_style)
    return svg_path1 + svg_path2

In [27]:
table_panel

In [28]:
make_path(table_panel, "", "")

'<path style="" d="M 0 105.0  L 0 7  Q 0 0 7 0  L 613 0 Q 620 0 620 7  L 620 105.0 "> </path> <path style="" d="M 620 105.0  L 620 413.0 Q 620 420.0 613 420.0  L 7 420.0 Q 0 420.0 0 413.0 L 0 105.0 "> </path> '

In [29]:
svg_chunk = """<svg version="1.1" xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0"
width="800" height="500" viewBox="0 0 650 500">
{defs}
  <g id="Layer_1">
    <g>{foreign_object_wrapper}
   
    </g>
  </g>
  {extras}
  </svg>
    """

In [30]:
HTML(svg_chunk.format(defs="", contents=make_path(table_panel, "", ""), extras="",foreign_object_wrapper=foreign_object_wrapper))

In [31]:
t = svg_chunk.format(defs="", contents=make_path(table_panel, "", ""), extras="",foreign_object_wrapper=foreign_object_wrapper)

In [32]:
with open("table.svg", "w") as tsvgf:
    tsvgf.write(t)